storybook:
  extends:
    file: docker-compose-common.yml
    service: webapp
  command: yarn run storybook
  ports:
    - "6006:6006"
browser-sync:
  extends:
    file: docker-compose-common.yml
    service: webapp
  command: yarn run start
  ports:
    - "3000:3000"
    - "3001:3001"
