storybook:
  build: .
  volumes:
    - .:/home/app/book-viewer
  command: yarn run storybook
  ports:
    - "6006:6006"
browser-sync:
  build: .
  volumes:
    - .:/home/app/book-viewer
  command: yarn run start
  ports:
    - "3000:3000"
    - "3001:3001"
